### ISSUE TITLE
Sample demo 

### ISSUE THREAD

**Issue by Goule** [odyshewroman/AndroidTVRemoteControl#1]
Hello @odyshewroman,

Many thanks for this library !!

Do you have any sample project for demo ? 

I'm a bit lost with certificate logic and it can help a lot of people I think ! 

Thanks

**Comment by odyshewroman** [comment]
Thanks, I thought that the description would be enough. But if necessary, I'll provide an example in the next few days.

**Comment by odyshewroman** [comment]
@Goule I've just added a demo project that allows you to run the Netflix app. Don't forget to add the IP address of your Android TV device.

**Comment by thachonline** [comment]
@odyshewroman 
Thank you for the demo project
Can you give more instructions related to power and send code(RemoteKeyCode) using RemoteManager?

**Comment by odyshewroman** [comment]
@thachonline, in generally right, but it depends on case. You use long press, but in my cases I usually use short press, but the using approach is right. And the data format too. For example I use format like this for Enter press - `[0x52, 0x04, 0x08, 0x42, 0x10, 0x03]`

When I have time I will implement high-level functions for sending commands and add it to the project

**Comment by Goule** [comment]
> @Goule I've just added a demo project that allows you to run the Netflix app. Don't forget to add the IP address of your Android TV device.

Perfect thanks !!
