### ISSUE TITLE
Getting noServerPublicCertificate error in sendSecret

### ISSUE THREAD

**Issue by Jacky154** [odyshewroman/AndroidTVRemoteControl#15]
Hi @odyshewroman 

I am getting the **noServerPublicCertificate** in sendSecret function in PairingManager file.

Can you tell me how to resolve it

Bro, I urgently have to solve it.

**Comment by odyshewroman** [comment]
Looks like the Android TV OS device doesn't have certificate, so device not support this remote control feature. You can easy check it by command `openssl s_client -connect SERVER_IP:6467 -prexit -state -debug`

or try download cert 
`openssl s_client -showcerts -connect SERVER_IP:6467 </dev/null 2>/dev/null|openssl x509 -outform PEM > server.pem`
If these functions fail, this will confirm that there are problems with the certificate on the device side.

**Comment by Jacky154** [comment]
I am getting this

Last login: Tue Jan  9 08:49:58 on console
admin@admins-iMac ~ % openssl s_client -connect 192.169.29.199:6467 -prexit -state -debug
connect: Operation timed out
connect:errno=60
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
---
admin@admins-iMac ~ % openssl s_client -showcerts -connect SERVER_IP:6467 </dev/null 2>/dev/null|openssl x509 -outform PEM > server.pem
unable to load certificate
8604676672:error:09FFF06C:PEM routines:CRYPTO_internal:no start line:/AppleInternal/Library/BuildRoots/11aa8fb2-5f4b-11ee-bc7f-926038f30c31/Library/Caches/com.apple.xbs/Sources/libressl/libressl-3.3/crypto/pem/pem_lib.c:694:Expecting: TRUSTED CERTIFICATE

**Comment by Jacky154** [comment]
I also connected with the same tv before and getting not any error. Later I change the connect function for getting code everytime. I reached at **waitingCode** state but then get error **noServerPublicCertificate** in **sendSecret** function. I also change the certificates means download the certificates again from your code and use them in code

**Comment by Jacky154** [comment]
I have reset the android device. Now I am getting this error **connectionWaitingError(-9825: misc. bad certificate)**

**Comment by Jacky154** [comment]
After running your demo I get new error 

**connection WaitingError: The operation could not be completed (Network.NWError error -65554 - NoSucRecord)**

**Comment by odyshewroman** [comment]
> I am getting this
> 
> **openssl s_client -connect 192.169.29.199:6467 -prexit -state -debug**
> 
> connect: Operation timed out connect:errno=60 no peer certificate available No client certificate CA names sent SSL handshake has read 0 bytes and written 0 bytes New, (NONE), Cipher is (NONE) Secure Renegotiation IS NOT supported Compression: NONE Expansion: NONE No ALPN negotiated
> 
> **openssl s_client -showcerts -connect 192.169.29.199:6467 </dev/null 2>/dev/null|openssl x509 -outform PEM > server.pem**
> 
> unable to load certificate 8604676672:error:09FFF06C:PEM routines:CRYPTO_internal:no start line:/AppleInternal/Library/BuildRoots/11aa8fb2-5f4b-11ee-bc7f-926038f30c31/Library/Caches/com.apple.xbs/Sources/libressl/libressl-3.3/crypto/pem/pem_lib.c:694:Expecting: TRUSTED CERTIFICATE

Q.E.D.

**Comment by Jacky154** [comment]
> After running your demo I get new error
> 
> **connection WaitingError: The operation could not be completed (Network.NWError error -65554 - NoSuchRecord)**
> 
> check image through link:
> 
> https://ibb.co/qypbkzV

What I do now ?

**Comment by odyshewroman** [comment]
Nothing

> Looks like the Android TV OS device doesn't have certificate, so device not support this remote control feature.

It's clear?

**Comment by Jacky154** [comment]
But as I said, I already connected with this tv like 3 months ago, when you upload this project and this works great. But now when I reset the android tv and again connect with your latest project I am getting error which I describe above with image.

**Comment by odyshewroman** [comment]
It's a lie. 
Or perhaps a factory reset was performed, and Android TV remote control TV App was downgraded to not supported version.
