### ISSUE TITLE
Not Working when call connect function

### ISSUE THREAD

**Issue by RehmanAli34** [odyshewroman/AndroidTVRemoteControl#16]
Hi @odyshewroman 

Thanks for this great library. I am using it to controlling my sony bravia. It is working perfectly.

But when I connect it with another android tv devices then after connect it do not works. It show code on tv but after that nothing happens.

I try to use disconnect function for disconnecting and reconnecting but do not works.

**Comment by odyshewroman** [comment]
Firstly, you should make sure that your device has a certificate. To do this, you should run the following command:

`openssl s_client -connect SERVER_IP:6467 -prexit -state -debug`

If the certificate exists, you should use PairingManager with a logger. There is a default logger in the Demo project.

When you send the code from the TV screen, you should see the following messages in the logs:

```
code: <your code>
Sending data: <data>
Success sent
```
If you see this, everything is okay.

Which state of the pairing manager have you got after sending the code?

**Comment by RehmanAli34** [comment]
I think there is some type of certificate error. I have run that openssl command in terminal and yes there is public certificate in my tv device. 
But Now I stuck at the state of .waitingCode, code shown on screen but when I send code to tv using sendCode function Nothing happend nor any logs.

Can you check, this is the project. 

[TVController(28).zip](https://github.com/odyshewroman/AndroidTVRemoteControl/files/13888519/TVController.28.zip)

**Comment by odyshewroman** [comment]
You can change your nickname, but you can't escape from yourself. 
There's no point in searching for errors where there are none. 
You create two different instances of the RemoteManager object on different screens. In one instance, you invoke the connect method, while you send the code in a completely different instance, and you didn't even bother to do a simple debug. 

I think I've earned more than a cup of coffee, haven't I?
[![Support](https://img.shields.io/badge/Support-Buy%20Me%20a%20Coffee-brightgreen.svg)](https://www.buymeacoffee.com/odyshewroman)

**Comment by RehmanAli34** [comment]
I think that idiot developer contact with you. I have assign him task of creating an app using this project, and he contacts with you before.

Sorry for that and also I send you project after think social.

I run that app on my home tv (Sony) it works but today when I run this in my friend tv it first not connect, then connect but reaches only at .WaitingCode state. 

I will buy you a coffee but first kindly solve that problem. You said there are two instance in two screens but tell me why it works on sony? Also tell me, I checked the code and there in WriteCodeVC.swift file I check that connect and pairing perform in one file in one screen so why two instance. You should check the sendCode function I think there is error.

Thanks for your help

**Comment by odyshewroman** [comment]
So funny...
I think the Sony TV worked because it was already connected to the app; in this case, the pairing process is not necessary. The RemoteTVManager instance is created on DeviceListVC and on WriteCodeVC, they are two different instances. You can easily check it by using the search function; that's the problem.

**Comment by RehmanAli34** [comment]
Thanks for help

I think you do not check the code carefully there is not any instance of remoteManager in devicelistVC. That is only in WriteCodeVC.

**Comment by odyshewroman** [comment]
Not RemoteManager, but RemoteTVManager, it's a different entities. 
![Снимок экрана 2024-01-10 в 23 53 04](https://github.com/odyshewroman/AndroidTVRemoteControl/assets/50772910/5fc5666f-d2d6-400b-a881-ecb7e34ee976)
21 line

**Comment by RehmanAli34** [comment]
Thanks

But I think it won't help to remove this instance.
As in next screen again connecting and pairing  so previous screen remoteTVManager instance do not effect anymore.

However I tried it on my model but still it stuck at .WaitingCode state. Have you tried this project on your tv model.

**Comment by odyshewroman** [comment]
I didn't write about removing instance, I have wrote about duplication instances issue.
It will 100% work, if you solve this issue, I tired to write about it several times.

**Comment by RehmanAli34** [comment]
As I said it is not working. I solve that duplicate instance issue but now I am receiving  error when use connect function 
**connectionWaitingError(-9836: Optional(bad protocol version))**

Here is the upgraded code can you check it please
[TVController(28).zip](https://github.com/odyshewroman/AndroidTVRemoteControl/files/13900743/TVController.28.zip)

**Comment by odyshewroman** [comment]
Are you kidding me? This code even not compile.
It's not depend on Android TV version, it's depend on version of Android TV Remote Service application, it should be version 5 or above. You can update this applicaton if necessary.

Look, are you can read? I have messaged you several times, but you fully ignore my advices and messages, and still banging your head against the wall.
I think, in this case you should be software developer, for implement this project, just being a coder is not enough.

**Comment by RehmanAli34** [comment]
I appreciate your response, you are a good person.

Look I am not a developer or coder. I have  slight knowledge of swift. I handle this project to developer on freelancing site and give the link of your project so that he easily manage it. But after testing, it gives me error which I described above.

I try to communicate to that developer again and again but he is not responding.

You are only hope because you develop this library and you know it more. I made a mistake I have to hire you instead that dumbest developer. But now I would be thankful to you if you resolve that error and test it.

You can kept that project for use if you want. I will give you money but I need to complete this project till today.

**Comment by odyshewroman** [comment]
This code has several issues. Apart from creating different instances of RemoteTVManager, the connect function is invoked multiple times consecutively.

In the DeviceListVC, when you select a row in the tableView.
Then the viewDidLoad function in WriteCodeVC is called, which in turn invokes the checkConnectionStatus function, where the connect function of RemoteTVManager is called again.

For some reason, your viewDidLoad function is called three times, leading to three consecutive calls to the connect function, which, of course, causes network issues.

I'm not sure that the project doesn't contain more issues. The codebase is so dirty, with a lot of unnecessary code, huge commented-out sections, and the use of my library in an old version where logs are still missing, which would greatly facilitate understanding the current situation.

**Comment by RehmanAli34** [comment]
Thanks 

But I want to give this project to you for bug fix and testing and want to know your budget and method of pay.

I think there is problem in first version 2.3.5 Can you tell me I am getting this error.

![error](https://github.com/odyshewroman/AndroidTVRemoteControl/assets/156180640/15eb1c6a-0a43-446f-966a-f265f4c664a3)

**Comment by odyshewroman** [comment]
Regarding this problem, I believe it has occurred because the device does not support this remote control technology. There could be several reasons for this:

It's a device with Android OS but not Android TV OS.
The version of the Remote Service application is less than 5. This could happen, for example, if you have reset the device to factory settings. In this case, you should simply update the Remote Service application on your device.
The device lacks certificates. You can check my messages on previous issue for information on how to verify this.
For development-related matters, please contact me via email odyshewroman@gmail.com

**Comment by RehmanAli34** [comment]
Ok thanks, 

By the way that is android tv OS with android version 9, there is android tv remote service app already installed and updated version (greater than v5), also through openssl commands I get that public certificates.

But still getting that network error.

I am testing it on OnePlus.
