### ISSUE TITLE
Certificate handling

### ISSUE THREAD

**Issue by Goule** [odyshewroman/AndroidTVRemoteControl#2]
Hello, 

Thanks for the sample demo ! 
I've tried it but I'm facing to an error : 

<img width="1850" alt="Screenshot 2023-10-23 at 12 51 43" src="https://github.com/odyshewroman/AndroidTVRemoteControl/assets/21126201/68f65ba1-c9c3-48c0-bdf1-1ab0c40cd2d0">

I thought it was a certificate problem, so I tried https://github.com/svdo/swift-SecurityExtensions to generate a certificate from the application.

Here is the code (edited from the sample):

```swift
init() {
        let cryptoManager = CryptoManager()
        
       let identity = SecIdentity.create(
            subjectCommonName: "test",
            subjectEmailAddress: "tests@gmail.com"
       )
//
        cryptoManager.clientPublicCertificate = {
//            guard let url = Bundle.main.url(forResource: "cert", withExtension: "der") else {
//                return .Error(.loadCertFromURLError(MyError.certNotFound))
//            }
//            
//            return CertManager().getSecKey(url)
            
            guard let publicKey = identity?.certificate?.publicKey else {
                return .Error(.loadCertFromURLError(MyError.certNotFound))
            }
            return .Result(publicKey)
        }
        
        let tlsManager = TLSManager {
//            guard let url = Bundle.main.url(forResource: "cert", withExtension: "p12") else {
//                return .Error(.loadCertFromURLError(MyError.certNotFound))
//            }
            
            guard let certData = identity?.certificate?.data else {
                return .Error(.loadCertFromURLError(MyError.certNotFound))
            }
            return CertManager().cert(certData, "")
        }
        
        tlsManager.secTrustClosure = { secTrust in
            cryptoManager.serverPublicCertificate = {
                guard let publicKey = SecTrustCopyKey(secTrust) else {
                    return .Error(.secTrustCopyKeyError)
                }
                
                return .Result(publicKey)
            }
        }
        
        pairingManager = PairingManager(tlsManager, cryptoManager)
        remoteManager = RemoteManager(tlsManager, CommandNetwork.DeviceInfo("client", "iPhone", "1.0.0", "example_app", "235"))
    }
```

Do you think it is a good approach to have a certificate created from each device?
A bit like on https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Google-TV-(aka-Android-TV)-Remote-Control-(v2)#clients-certificate

Thanks !

**Comment by odyshewroman** [comment]
Oh my, I'm having issues with the certificate from the project? And generating a certificate also didn't work? There shouldn't be any problems. It might be that the device doesn't have its own certificate. I've encountered this once before when dealing with the Chinese TV brand CooCaa, as they didn't provide a certificate. Therefore, it's not possible to establish a connection with them. Also, you shouldn't confuse Android OS and Android TV OS; this approach only works with Android TV OS. Can you provide details about the device you're trying to connect to? The brand, name, and model?

Regarding the approach of obtaining a certificate - from resources, a server, or generating it in real-time - it's up to you. However, I think if you generate a certificate for each new connection, you will have to go through the pairing process every time. If you will use the same certificate next time, you can try connecting to the device without pairing. Nevertheless, you can also use a certificate created from code; just store it in the keychain or some other storage.

**Comment by Goule** [comment]
I'm trying to connect on a [Smart Tech TV ](https://www.amazon.fr/Smart-ANDROID-DVB-T2-H-265-3xHDMI/dp/B09PR763GJ/ref=sr_1_3_sspa?__mk_fr_FR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=73M2RP7WB1OS&keywords=smart+tech+tv&qid=1698092561&sprefix=smart+tech+tv%2Caps%2C112&sr=8-3-spons&ufe=app_do%3Aamzn1.fos.49fccda8-a887-4188-817b-b9a64bb30e43&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1) for testing purpose. 

It is the same issue with the newly generated cert. 

I tried with another [TV Remote on the store ](https://apps.apple.com/fr/app/t%C3%A9l%C3%A9commande-tv/id1570275114) and it work ! 
I will try to find a solution but it's really hard to debug :)

**Comment by odyshewroman** [comment]
@Goule I've figured out what's causing the problem. I have uploaded a fix, please update to the latest commit and try the Demo again.

In this example, I wanted to implement the idea that after the first successful pairing, you will not need to pair again the next time.

**Comment by Goule** [comment]
Hello @odyshewroman ,

I tried the demo but still the same issue. 
But in my case the pairing has never been made, so it's normal that the remoteManager connexion fail. 

I've tried to make only the pairing and printing the pairingResponse data: 

<img width="2136" alt="Screenshot 2023-10-24 at 09 50 54" src="https://github.com/odyshewroman/AndroidTVRemoteControl/assets/21126201/286878f2-affa-4189-8cc8-b33558606da2">

In this case the pairing code is never shown on the TV

**Comment by odyshewroman** [comment]
@Goule you have a new TV model, and I doubt that it uses the first version of the protocol. In any case, you can check this by looking at the version of the Remote Services application (in Settings > Apps > See all apps > Android TV Remote Service); the version should be greater than or equal to five.

In any case, your situation is interesting. Try modifying the connect function by keeping only the code related to pairing.

```
func connect(host: String) {
        queue.async {
            self.pairingManager.stateChanged = { [weak self] pairingState in
                self?.pairingStateChanged?(pairingState.toString())
                
                if case .successPaired = pairingState {
                    self?.remoteManager.connect(host)
                }
            }
            
            self.pairingManager.connect(host, "client", "iPhone")
        }
    }
```

 Do you reach a state where the smart TV displays a code?

**Comment by Goule** [comment]
Everything is working after a system update ! 
Before the update I was on the version 9, now on the version 11...
