### ISSUE TITLE
Can I use this in swiftUI

### ISSUE THREAD

**Issue by Coger541** [odyshewroman/AndroidTVRemoteControl#29]
Hello,
Sorry for this silly question as I am a noob in iOS development.

I wanna just ask that this library is made in UIKit so can I use this library in my SwiftUI project ?

**Comment by odyshewroman** [comment]
Yes. There are no any UIKit imports or requirements. Just one thing, I use GCD for concurrency, but you can add necessary functions as extension and implement structured concurrency approach.

**Comment by Coger541** [comment]
Hello @odyshewroman 
Thanks man 

If I understand it correctly then if I don't want structured concurrency approach then still can I use this library into my SwiftUI without any change in project ?

**Comment by odyshewroman** [comment]
Yep

**Comment by Coger541** [comment]
Ok thanks
