### ISSUE TITLE
How to find App DeepLink

### ISSUE THREAD

**Issue by Coger541** [odyshewroman/AndroidTVRemoteControl#30]
Hi @odyshewroman 

I have seen there is a function to open app like YouTube, Disney, Netflix etc but where to find out their DeepLink for all apps.

**Comment by odyshewroman** [comment]
Hi @Coger541 
There is no way to getting list of installed app, so you should be sure that app that you wanna start is installed.
And you should know the deeplink before launch it, there is some reourses where people share the lists of apps deeplink, like this one https://community.home-assistant.io/t/android-tv-remote-app-links-deep-linking-guide/567921

**Comment by Coger541** [comment]
Ok thanks
